begin;
select plan(89);

select has_table('public','memberships','memberships table exists');
select has_function('app','can_access',array['uuid','uuid','text','text'],'tenant authorization function exists');
select policies_are('public','audit_log',array['audit_log_select'],'audit log exposes read-only policy');
select triggers_are('public','protocol_versions',array['protocol_versions_immutable','protocol_versions_audit','protocol_versions_protocol_id_scope','protocol_versions_outbox'],'published protocol versions are protected, audited, synchronized and tenant-scoped');
select has_trigger('public','audit_log','audit_log_append_only','audit records cannot be mutated');
select has_function('public','commit_import_job',array['uuid'],'validated imports commit transactionally');
select has_function('public','register_device',array['uuid','text','text'],'device registration is server-controlled');
select has_table('public','import_jobs','import previews are persisted');
select has_function('public','approve_protocol_version',array['uuid','integer','uuid'],'protocol approval is an explicit command');
select has_function('public','publish_protocol_version',array['uuid','integer','uuid'],'protocol publication is idempotent and versioned');
select has_function('public','complete_execution',array['uuid','integer','uuid','jsonb'],'execution completion is transactional');
select has_function('public','open_measurement_plan',array['uuid','integer','uuid','jsonb'],'deviations create plans transactionally');
select has_function('public','complete_meeting',array['uuid','integer','uuid','text'],'meeting completion is transactional');
select has_function('app','emit_domain_change',array[]::text[],'domain mutations emit an outbox event');
select has_trigger('public','knowledge_items','knowledge_items_outbox','knowledge changes participate in synchronization');
select has_table('public','protocol_indicator_bindings','published protocol versions can feed governed indicators');
select has_function('app','formula_ast_is_valid',array['jsonb','integer'],'formula AST validation exists in the database');
select has_function('app','evaluate_formula_ast',array['jsonb','jsonb','integer'],'formula evaluation is server-controlled');
select has_function('public','create_indicator_formula_version',array['uuid','integer','uuid','jsonb','jsonb','date'],'formula version creation is transactional');
select has_function('public','bind_protocol_indicator',array['uuid','integer','uuid','uuid','uuid','uuid'],'protocol-to-indicator binding is explicit');
select has_trigger('public','indicator_formula_versions','indicator_formula_versions_immutable','formula versions cannot be changed');
select has_table('public','indicator_deviation_policies','indicator deviation automation is governed by policy');
select has_function('app','ensure_measurement_deviation_plan',array['uuid'],'out-of-target measurements can create treatment automatically');
select has_trigger('public','measurements','measurements_auto_deviation','measurement deviations invoke the governed treatment flow');
select has_function('public','complete_action',array['uuid','integer','uuid','uuid'],'5W2H action completion is an explicit command');
select has_function('public','record_plan_effectiveness',array['uuid','integer','uuid','boolean','text','uuid'],'effectiveness review is an explicit command');
select triggers_are('public','indicator_deviation_policies',array['indicator_deviation_policies_touch','indicator_deviation_policies_scope','indicator_deviation_policies_audit','indicator_deviation_policies_outbox'],'deviation policies are versioned, scoped, audited and synchronized');
select has_function('public','start_meeting',array['uuid','integer','uuid'],'meeting start is an explicit command');
select has_function('public','convert_referral_to_action',array['uuid','integer','uuid'],'referral conversion is idempotent and transactional');
select has_trigger('public','meeting_participants','meeting_participants_user_scope','participants must belong to the meeting scope');
select has_trigger('public','referrals','referrals_responsible_scope','referral assignees must belong to the meeting scope');
select has_trigger('public','meeting_agenda_items','meeting_agenda_items_audit','agenda changes are audited');
select has_trigger('public','meeting_participants','meeting_participants_audit','attendance changes are audited');
select has_function('public','publish_audit_model',array['uuid','integer','uuid'],'audit model publication is explicit and versioned');
select has_function('public','start_audit_execution',array['uuid','integer','uuid'],'audit execution start is explicit and versioned');
select has_function('public','complete_audit_execution',array['uuid','integer','uuid','jsonb'],'audit completion is transactional');
select has_trigger('public','audit_model_versions','audit_model_versions_immutable','published audit models are protected');
select has_trigger('public','audit_model_versions','audit_model_versions_audit','audit model changes are audited');
select has_trigger('public','audit_model_versions','audit_model_versions_outbox','audit model changes participate in synchronization');
select has_function('public','move_asset',array['uuid','integer','uuid','text','text'],'asset transfers are transactional');
select has_function('public','record_stock_movement',array['uuid','integer','uuid','text','numeric','text'],'stock balance changes are transactional');
select has_trigger('public','asset_movements','asset_movements_audit','asset movements are audited');
select has_trigger('public','stock_movements','stock_movements_audit','stock movements are audited');
select col_is_pk('public','stock_movements','id','stock movements have immutable identifiers');
select has_column('public','stock_batches','quantity','stock balance is kept by batch');
select has_function('public','transition_maintenance_order',array['uuid','integer','uuid','text'],'maintenance transitions update work order and asset atomically');
select has_function('public','refresh_due_notifications',array[]::text[],'operational alerts share an idempotent scheduled processor');
select col_has_check('public','maintenance_orders','status','maintenance states are constrained');
select col_has_check('public','stock_batches','quantity','batch stock cannot become negative');
select has_table('public','sensitive_access_log','sensitive consultations have a dedicated audit trail');
select has_trigger('public','sensitive_access_log','sensitive_access_log_append_only','sensitive access records are append-only');
select has_function('app','feature_enabled',array['uuid','uuid','text'],'sensitive gates are enforced in the database');
select has_function('public','read_sensitive_records',array['text','uuid','integer','uuid','text'],'sensitive reads are audited');
select has_function('public','analyze_safety_event',array['uuid','integer','uuid','text','text','boolean'],'patient safety analysis is explicit');
select has_function('public','respond_ombudsman_case',array['uuid','integer','uuid','text','text'],'ombudsman response is explicit');
select col_has_check('public','safety_events','status','patient safety states are constrained');
select col_has_check('public','ombudsman_cases','status','ombudsman states are constrained');
select has_function('public','create_knowledge_version',array['uuid','integer','uuid','jsonb','jsonb','date','date'],'knowledge versions are created transactionally');
select has_function('public','transition_knowledge_version',array['uuid','integer','uuid','text'],'knowledge lifecycle transitions are explicit');
select has_function('public','create_protocol_version',array['uuid','integer','uuid','jsonb','date','date'],'protocol versions are created transactionally');
select has_function('public','submit_protocol_review',array['uuid','integer','uuid'],'protocol review submission is explicit');
select has_function('public','start_protocol_execution',array['uuid','uuid','uuid','uuid'],'execution start preserves the published protocol version');
select has_table('public','attachment_access_log','evidence downloads have a dedicated audit trail');
select has_trigger('public','attachment_access_log','attachment_access_log_append_only','evidence access records are immutable');
select has_function('public','reserve_attachment',array['uuid','uuid','uuid','text','text','text','bigint','text','text','text','uuid','text'],'evidence metadata and link are reserved atomically');
select has_function('public','finalize_attachment',array['uuid','integer','bigint','text'],'uploaded evidence integrity is verified');
select has_function('public','record_attachment_access',array['uuid','uuid','text'],'evidence downloads are audited');
select has_column('public','critical_analyses','action_plan_id','critical analysis can reference its treatment plan');
select has_function('public','record_critical_analysis',array['uuid','integer','uuid','text','text','text','uuid'],'critical analysis is version checked and transactional');
select has_table('public','action_comments','action updates preserve comments');
select has_trigger('public','action_comments','action_comments_audit','action comments are audited');
select has_function('public','update_action',array['uuid','integer','uuid','jsonb'],'action updates enforce justification and optimistic locking');
select has_function('public','mark_notification_read',array['uuid'],'notification reading does not resolve the alert');
select policies_are('public','action_comments',array['action_comments_select','action_comments_insert'],'action comments expose no destructive policy');
select has_trigger('public','audit_executions','audit_executions_validate_completion','required audit evidence is validated before completion');
select has_table('public','coverage_requirements','staffing coverage is institutionally parameterized');
select has_function('public','people_coverage',array['uuid','timestamp with time zone','timestamp with time zone'],'people coverage is calculated server-side');
select has_table('public','asset_inventories','asset inventory campaigns are persisted');
select has_table('public','asset_inventory_items','asset counts preserve per-item evidence');
select has_function('public','start_asset_inventory',array['uuid','integer','uuid'],'asset inventory snapshot start is transactional');
select has_function('public','complete_asset_inventory',array['uuid','integer','uuid'],'asset inventory completion reports discrepancies');
select has_table('public','stock_inventories','stock inventory campaigns are persisted');
select has_function('public','record_stock_inventory_count',array['uuid','uuid','numeric','text'],'stock physical counts preserve expected balance');
select has_function('public','complete_stock_inventory',array['uuid','integer','uuid','boolean','text'],'stock inventory adjustments are explicit and auditable');
select has_function('public','provision_invited_membership',array['uuid','uuid','uuid','text','text[]','text[]'],'invite membership provisioning is governed');
select has_function('public','set_feature_flag',array['uuid','uuid','text','boolean','text'],'feature flags change through an authorized command');
select is(
  app.evaluate_formula_ast('{"type":"binary","operator":"*","left":{"type":"binary","operator":"/","left":{"type":"variable","name":"conformes"},"right":{"type":"variable","name":"total"}},"right":{"type":"literal","value":100}}'::jsonb,'{"conformes":23,"total":25}'::jsonb),
  92::numeric,
  'database formula engine computes a governed percentage'
);
select is(app.classify_against_target(92,'GTE',95,null,null,'{"value":90}'::jsonb),'ATENCAO','target classification preserves the attention band');
select ok(not app.formula_ast_is_valid('{"type":"binary","operator":"eval"}'::jsonb),'arbitrary operators are rejected in the database');

select * from finish();
rollback;
