import { expect, test } from "@playwright/test";

test("dashboard and module navigation remain actionable", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "O que exige atenção hoje?" })).toBeVisible();
  await page.getByRole("link", { name: /Protocolos/ }).first().click();
  await expect(page.getByRole("heading", { name: "Protocolos gerenciais" })).toBeVisible();
  await page.getByPlaceholder("Pesquisar registros...").fill("medicamentos");
  await expect(page.getByText("Verificação de medicamentos próximos ao vencimento")).toBeVisible();
  await page.getByRole("button", { name: "Criar protocolo" }).click();
  await expect(page.getByRole("dialog", { name: "Criar protocolo" })).toBeVisible();
  await page.getByLabel("Código").fill(`TEST-${Date.now()}`);
  await page.getByLabel("Título").fill("Protocolo criado pelo teste de jornada");
  const created = page.waitForResponse((response) => response.url().endsWith("/api/v1/protocols") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Salvar rascunho" }).click();
  expect((await created).status()).toBe(201);
  await expect(page.getByRole("status")).toContainText("Registro criado com sucesso");
  await expect(page.getByRole("dialog", { name: "Criar protocolo" })).toBeHidden();
  await page.getByRole("button", { name: "Sincronização" }).click();
  await expect(page.getByRole("dialog", { name: "Cofre offline deste dispositivo" })).toBeVisible();
  await page.getByLabel("PIN local de 6 a 12 dígitos").fill("123");
  await page.getByRole("button", { name: "Desbloquear cofre" }).click();
  await expect(page.getByRole("status")).toContainText("6 a 12 dígitos");
  await page.getByRole("button", { name: "Fechar" }).click();
  await page.goto("/reunioes");
  await page.getByRole("button", { name: "Abrir Reunião mensal da equipe" }).click();
  await expect(page.getByRole("dialog").getByText("Agendada · 3 pendências")).toBeVisible();
  await page.getByRole("button", { name: "Iniciar reunião" }).click();
  await expect(page.getByRole("status")).toContainText("Reunião iniciada");
});
