import { expect, test } from "@playwright/test";

test("dashboard and module navigation remain actionable", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Prioridades da unidade" })).toBeVisible();
  await page.getByRole("link", { name: "Protocolos", exact: true }).first().click();
  await expect(page.getByRole("heading", { name: "Protocolos gerenciais" })).toBeVisible();
  await page.getByRole("textbox", { name: "Pesquisar" }).fill("medicamentos");
  await page.getByRole("button", { name: "Aplicar filtros" }).click();
  await expect(page.getByText("Verificação de medicamentos próximos ao vencimento")).toBeVisible();
  await page.getByRole("link", { name: "Criar protocolo" }).click();
  await expect(page.getByRole("heading", { name: "Criar protocolo" })).toBeVisible();
  await page.getByLabel("Código").fill(`TEST-${Date.now()}`);
  await page.getByLabel("Título").fill("Protocolo criado pelo teste de jornada");
  await page.getByLabel("Domínio institucional").fill("HOMOLOGACAO");
  const created = page.waitForResponse((response) => response.url().endsWith("/api/v1/protocols") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Salvar e continuar" }).click();
  expect((await created).status()).toBe(201);
  await expect(page).toHaveURL(/\/registros\/protocols\//);
  await expect(page.getByRole("heading", { name: "Informações do registro" })).toBeVisible();
  await page.getByRole("button", { name: "Sincronização" }).click();
  await expect(page.getByRole("dialog", { name: "Cofre offline deste dispositivo" })).toBeVisible();
  await page.getByLabel("PIN local de 6 a 12 dígitos").fill("123");
  await page.getByRole("button", { name: "Desbloquear cofre" }).click();
  await expect(page.getByRole("dialog").getByRole("status")).toContainText("6 a 12 dígitos");
  await page.getByRole("button", { name: "Fechar" }).click();
  await page.goto("/reunioes");
  await page.getByRole("link", { name: "Abrir Reunião mensal da equipe" }).click();
  await expect(page).toHaveURL(/\/registros\/meetings\//);
  await expect(page.getByRole("definition").filter({ hasText: /^Agendada$/ })).toBeVisible();
  await page.getByRole("button", { name: "Iniciar reunião" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Salvo e confirmado pelo servidor." })).toBeVisible();
});
