"use client";
import Link from "next/link";
import { useState } from "react";
import type { DetailData, DetailRow } from "@/lib/server/record-detail";
import type { WorkspaceContext } from "@/lib/server/workspace";
import { CommandForm, type CommandField } from "@/components/record-command-form";
import { FormulaBuilder } from "@/components/record-formula-builder";
import { RecordEvidence } from "@/components/record-evidence";
import { DraftWorkspace } from "@/components/draft-tools";
import { z } from "zod";

export { CommandForm } from "@/components/record-command-form";
const str = (value: unknown) => value === null || value === undefined ? "" : String(value);
const obj = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const labels: Record<string, string> = { DRAFT: "Rascunho", RASCUNHO: "Rascunho", IN_REVIEW: "Em revisão", EM_REVISAO: "Em revisão", APPROVED: "Aprovado", APROVADO: "Aprovado", PUBLISHED: "Publicado", PUBLICADO: "Publicado", OPEN: "Aberto", IN_PROGRESS: "Em andamento", COMPLETED: "Concluído", CONCLUIDO: "Concluído", CLOSED: "Encerrado", FORA_META: "Fora da meta", DENTRO_META: "Dentro da meta", SEM_DADO: "Sem dado", ATENCAO: "Atenção", SCHEDULED: "Agendada", NAO_INICIADO: "Não iniciado", EM_ANDAMENTO: "Em andamento", BLOQUEADO: "Bloqueado", MINUTES_PENDING: "Ata pendente", ACTIVE: "Ativo", CANCELLED: "Cancelado", CANCELADO: "Cancelado", EFFECTIVENESS_PENDING: "Verificação de eficácia pendente" };
const titleFor = (row: DetailRow) => str(row.title || row.name || row.what || row.description || row.code || (row.version_number ? `Versão ${row.version_number}` : row.competency ? `Medição de ${row.competency}` : "Registro vinculado"));
const textField = (name: string, label: string, required = true): CommandField => ({ name, label, required, minLength: required ? 3 : undefined });
const dateField = (name: string, label: string, required = true): CommandField => ({ name, label, required, type: "date" });
const descriptionField = (name: string, label: string, required = true): CommandField => ({ ...textField(name, label, required), type: "textarea" });
const numberField = (name: string, label: string, required = true): CommandField => ({ name, label, required, type: "number" });
function readable(value: unknown): string {
  if (typeof value === "boolean") return value ? "Sim" : "Não";
  if (Array.isArray(value)) return value.map(readable).filter(Boolean).join("; ");
  if (value && typeof value === "object") {
    const record = obj(value);
    if (record.type === "variable") return str(record.name);
    if (record.type === "literal") return str(record.value);
    if (record.type === "binary") return `(${readable(record.left)} ${record.operator} ${readable(record.right)})`;
    return Object.entries(record).filter(([key]) => !key.endsWith("Id") && !key.endsWith("_id")).map(([key, item]) => `${key}: ${readable(item)}`).join(" · ");
  }
  return labels[str(value)] || str(value);
}

const draftFieldsSchema = z.array(z.object({ key: z.string().max(64), label: z.string().max(500), type: z.enum(["text", "number", "boolean"]), required: z.boolean() })).min(1).max(100);
function ChecklistBuilder({ id }: { id: string }) {
  const [fields, setFields] = useState([{ key: "", label: "", type: "text", required: true }]);
  return <CommandForm title="Salvar checklist desta versão" endpoint={`/api/v1/protocol-versions/${id}/forms`} extraDraft={{ value: JSON.stringify(fields), restore: value => { const parsed = draftFieldsSchema.safeParse(JSON.parse(value)); if (!parsed.success) throw new Error("O rascunho do checklist não é válido."); setFields(parsed.data); } }} fields={[textField("name", "Nome do checklist")]} transform={values => ({ ...values, fields })}>
    {fields.map((field, index) => <fieldset key={index}><legend>Campo {index + 1}</legend><label>Pergunta<input value={field.label} required onChange={event => setFields(items => items.map((item, i) => i === index ? { ...item, label: event.target.value } : item))} /></label><label>Identificador da resposta<input value={field.key} required pattern="[a-z][a-z0-9_]{0,63}" placeholder="ex.: quantidade_verificada" onChange={event => setFields(items => items.map((item, i) => i === index ? { ...item, key: event.target.value } : item))} /></label><label>Formato<select value={field.type} onChange={event => setFields(items => items.map((item, i) => i === index ? { ...item, type: event.target.value } : item))}><option value="text">Texto</option><option value="number">Número</option><option value="boolean">Sim ou não</option></select></label><label><input type="checkbox" checked={field.required} onChange={event => setFields(items => items.map((item, i) => i === index ? { ...item, required: event.target.checked } : item))} />Resposta obrigatória</label>{fields.length > 1 && <button type="button" className="secondary-button" onClick={() => setFields(items => items.filter((_, i) => index !== i))}>Remover campo {index + 1}</button>}</fieldset>)}
    <button type="button" className="secondary-button" disabled={fields.length >= 100} onClick={() => setFields(items => [...items, { key: "", label: "", type: "text", required: true }])}>Adicionar campo</button>
  </CommandForm>;
}

export function RecordDetail({ detail, workspace, returnTo }: { detail: DetailData; workspace: WorkspaceContext; returnTo: string }) {
  const { resource, record: row, related, choices } = detail;
  const version = Number(row.version ?? row.version_number ?? 1);
  const status = str(row.status);
  const can = (operation: string, domain = detail.module) => workspace.permissions.some(permission => (permission.domain === "*" || permission.domain === domain) && (permission.operations.includes("*") || permission.operations.includes(operation)));
  const selectedUnit = str(row.unit_id) || workspace.unitId;
  const recordUnitName = row.unit_id ? workspace.scopes.find(scope => scope.organizationId === workspace.organizationId && scope.unitId === row.unit_id)?.unitName ?? "UBS do registro" : "Escopo da organização";
  const endpoint = `/api/v1/${resource}/${row.id}`;
  const currentPath = `/registros/${resource}/${row.id}?returnTo=${encodeURIComponent(returnTo)}`;
  const options = (rows: DetailRow[] = []) => rows.map(item => ({ value: item.id, label: titleFor(item) }));
  const responsible: CommandField = { name: "responsibleId", label: "Responsável", options: options(choices.people), required: true, defaultValue: workspace.userId };
  const files = related.attachments ?? [];
  const evidenceField: CommandField = { name: "evidenceAttachmentId", label: "Evidência verificada", options: files.filter(file => file.status === "AVAILABLE").map(file => ({ value: file.id, label: str(file.file_name) })) };
  const link = (res: string, id: unknown, label: string) => typeof id === "string" ? <Link href={`/registros/${res}/${id}?returnTo=${encodeURIComponent(currentPath)}`}>{label} →</Link> : null;
  const forms = [...(related.forms ?? [])].sort((a, b) => Number(b.version_number) - Number(a.version_number)).slice(0, 1);
  const formFields = forms.flatMap(form => {
    const schema = obj(form.schema);
    return Array.isArray(schema.fields) ? schema.fields.map(obj) : [];
  });
  const responseFields: CommandField[] = formFields.map(field => ({ name: str(field.key || field.id), label: str(field.label), required: Boolean(field.required), type: field.type === "number" ? "number" : "text", ...(field.type === "boolean" ? { options: [{ value: "true", label: "Sim" }, { value: "false", label: "Não" }] } : {}), defaultValue: str((related.responses ?? []).find(response => response.field_key === (field.key || field.id))?.value) }));
  const activeBinding = (related.bindings ?? []).filter(binding => binding.status === "ACTIVE").sort((a, b) => Number(Boolean(b.unit_id)) - Number(Boolean(a.unit_id)))[0];
  const boundFormula = (choices.formulas ?? []).find(formula => formula.id === activeBinding?.formula_version_id);
  const variables = Array.isArray(boundFormula?.variables) ? boundFormula.variables.map(String) : [];
  const memberName = (id: unknown) => (choices.people ?? []).find(person => person.id === id)?.name ?? "Participante autorizado";
  const metadata: [string, unknown][] = [["Estado", labels[status] || status], ["Versão", row.version_number ?? row.version], ["UBS", recordUnitName], ["Código", row.code], ["Descrição", row.definition || row.description], ["Vigência inicial", row.valid_from], ["Vigência final", row.valid_until], ["Resultado", row.value], ["Competência", row.competency], ["Prazo", row.due_at || row.when_at], ["Progresso", row.percentage === undefined ? null : `${row.percentage}%`], ["Local", row.location || row.where_text], ["Por quê", row.why], ["Como", row.how], ["Custo", row.how_much]];
  return <DraftWorkspace.Provider value={workspace}><div className="content detail-layout"><Link className="link-button" href={returnTo}>← Voltar à lista</Link><header><span className="eyebrow">{workspace.unitName}</span><h1 className="page-title">{titleFor(row)}</h1><p>Consulte o histórico e execute a próxima etapa permitida para este registro.</p></header>
    <section className="panel detail-section"><h2>Informações do registro</h2><dl className="record-detail-grid">{metadata.filter(([, value]) => value !== undefined && value !== null && value !== "").map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{readable(value)}</dd></div>)}</dl>
      {row.content !== undefined && <div className="record-content"><h3>Conteúdo da versão</h3>{Object.entries(obj(row.content)).filter(([key]) => !key.endsWith("Id")).map(([key, value]) => <div key={key}><h4>{({ instructions: "Orientações", objective: "Objetivo", scope: "Aplicação", text: "Conteúdo", reference: "Referência" } as Record<string, string>)[key] ?? key}</h4><p style={{ whiteSpace: "pre-wrap" }}>{readable(value)}</p></div>)}</div>}
      {Boolean(row.minutes) && <><h3>Ata registrada</h3><p style={{ whiteSpace: "pre-wrap" }}>{str(row.minutes)}</p></>}
      {row.protocol_id ? link("protocols", row.protocol_id, "Protocolo de origem") : null}{row.knowledge_item_id ? link("knowledge", row.knowledge_item_id, "Documento de origem") : null}{row.protocol_version_id ? link("protocol-versions", row.protocol_version_id, "Versão executada") : null}{row.indicator_id ? link("indicators", row.indicator_id, "Indicador de origem") : null}{row.action_plan_id ? link("action-plans", row.action_plan_id, "Plano vinculado") : null}{row.meeting_id ? link("meetings", row.meeting_id, "Reunião de origem") : null}
    </section>
    {(["knowledge", "protocols"].includes(resource) && can("editar")) && <CommandForm title="Criar nova versão" endpoint={`${endpoint}/versions`} expectedVersion={version} redirectResource={resource === "knowledge" ? "knowledge-versions" : "protocol-versions"} fields={[descriptionField("instructions", "Conteúdo institucional"), dateField("validFrom", "Início da vigência"), dateField("validUntil", "Fim da vigência", false), ...(resource === "knowledge" ? [textField("reference", "Referência bibliográfica ou documental", false)] : [{ name: "knowledgeVersionId", label: "Conhecimento publicado de referência", options: options((choices.knowledge ?? []).filter(item => item.status === "PUBLISHED")) } as CommandField])]} transform={({ instructions, reference, knowledgeVersionId, ...values }) => ({ ...values, content: { instructions, ...(knowledgeVersionId ? { knowledgeVersionId } : {}) }, references: reference ? [{ title: reference }] : [] })} />}
    {resource === "knowledge-versions" && <>{status === "DRAFT" && can("editar") && <CommandForm title="Enviar para revisão" endpoint={`${endpoint}/transition`} expectedVersion={version} payload={{ targetStatus: "IN_REVIEW" }} />}{status === "IN_REVIEW" && can("aprovar") && <CommandForm title="Aprovar conteúdo" endpoint={`${endpoint}/transition`} expectedVersion={version} payload={{ targetStatus: "APPROVED" }} />}{status === "APPROVED" && can("publicar") && <CommandForm title="Publicar conteúdo" endpoint={`${endpoint}/transition`} expectedVersion={version} payload={{ targetStatus: "PUBLISHED" }} />}</>}
    {resource === "protocol-versions" && <>
      {status === "RASCUNHO" && can("editar") && <><ChecklistBuilder id={row.id} /><CommandForm title="Enviar protocolo para revisão" endpoint={`${endpoint}/submit-review`} expectedVersion={version} /></>}
      {status === "EM_REVISAO" && can("aprovar") && <CommandForm title="Aprovar protocolo" endpoint={`/api/v1/protocols/${row.id}/approve`} expectedVersion={version} />}
      {status === "APROVADO" && can("publicar") && <CommandForm title="Publicar protocolo" endpoint={`/api/v1/protocols/${row.id}/publish`} expectedVersion={version} />}
      {can("editar") && <CommandForm title="Vincular fórmula de indicador" endpoint={`${endpoint}/indicator-bindings`} expectedVersion={version} payload={{ unitId: selectedUnit }} fields={[{ name: "formulaVersionId", label: "Indicador e versão da fórmula", required: true, options: (choices.formulas ?? []).map(formula => ({ value: formula.id, label: `${titleFor((choices.indicators ?? []).find(indicator => indicator.id === formula.indicator_id) ?? formula)} · versão ${formula.version_number}` })) }]} transform={values => ({ ...values, indicatorId: (choices.formulas ?? []).find(formula => formula.id === values.formulaVersionId)?.indicator_id })} />}
      {status === "PUBLICADO" && can("executar") && <CommandForm title="Iniciar execução nesta UBS" endpoint={`${endpoint}/executions`} payload={{ unitId: selectedUnit }} fields={selectedUnit ? [] : [{ name: "unitId", label: "UBS da execução", required: true, options: workspace.scopes.filter(scope => scope.unitId && scope.organizationId === workspace.organizationId).map(scope => ({ value: scope.unitId!, label: scope.unitName })) }]} transform={values => ({ ...values, executionId: values.operationId })} redirectResource="executions" />}
    </>}
    {resource === "indicators" && <>{can("editar") && <FormulaBuilder indicatorId={row.id} version={version} />}{can("criar") && <CommandForm title="Cadastrar meta institucional" endpoint={`${endpoint}/targets`} payload={{ organizationId: workspace.organizationId, unitId: selectedUnit }} fields={[...(selectedUnit ? [] : [{ name: "unitId", label: "UBS da meta", required: true, options: workspace.scopes.filter(scope => scope.unitId && scope.organizationId === workspace.organizationId).map(scope => ({ value: scope.unitId!, label: scope.unitName })) } as CommandField]), dateField("startsOn", "Início da vigência"), dateField("endsOn", "Fim da vigência"), { name: "comparison", label: "Comparação", required: true, options: [{ value: "GTE", label: "Maior ou igual" }, { value: "LTE", label: "Menor ou igual" }, { value: "EQ", label: "Igual" }, { value: "BETWEEN", label: "Entre dois valores" }] }, numberField("targetValue", "Valor da meta (fora de intervalo)", false), numberField("minimumValue", "Limite mínimo (intervalo)", false), numberField("maximumValue", "Limite máximo (intervalo)", false)]} />}</>}
    {resource === "executions" && <>
      {["OPEN", "IN_PROGRESS", "REOPENED", "PENDING_SYNC"].includes(status) && can("executar") && responseFields.length > 0 && <CommandForm title="Salvar respostas do checklist" endpoint={`${endpoint}/responses`} expectedVersion={version} fields={responseFields} transform={values => ({ operationId: values.operationId, expectedVersion: values.expectedVersion, responses: responseFields.map(field => ({ fieldKey: field.name, value: values[field.name] == null ? null : field.options ? values[field.name] === "true" : values[field.name] })) })} />}
      {["OPEN", "IN_PROGRESS", "REOPENED", "PENDING_SYNC"].includes(status) && can("encerrar") && <CommandForm title="Concluir execução e calcular indicador" endpoint={`${endpoint}/complete`} expectedVersion={version} fields={[...variables.map(name => numberField(`input_${name}`, `Dado para cálculo: ${name}`)), descriptionField("notes", "Observações da execução", false)]} transform={values => ({ operationId: values.operationId, expectedVersion: values.expectedVersion, notes: values.notes, ...(variables.length ? { indicatorInputs: Object.fromEntries(variables.map(name => [name, values[`input_${name}`]])) } : {}), result: Object.fromEntries((related.responses ?? []).map(response => [str(response.field_key), response.value])) })}><p>{activeBinding ? "O servidor usa a fórmula e a meta vinculadas para gerar a medição." : can("visualizar", "indicadores") ? "Sem indicador vinculado visível: a conclusão não gerará uma medição." : "Seu perfil não pode consultar os vínculos de indicadores. Solicite ao responsável a apuração do resultado."} Salve as respostas antes de concluir.</p></CommandForm>}
    </>}
    {resource === "measurements" && <>{can("editar") && <CommandForm title="Registrar análise crítica" endpoint={`${endpoint}/analysis`} expectedVersion={version} fields={[descriptionField("analysis", "Análise do resultado"), descriptionField("cause", "Causa identificada", false), descriptionField("decision", "Decisão de acompanhamento")]} />}{status === "FORA_META" && can("criar", "melhoria") && <CommandForm title="Abrir desvio e plano de ação" endpoint={`${endpoint}/open-plan`} expectedVersion={version} redirectResource="action-plans" fields={[textField("title", "Título do plano"), descriptionField("description", "Descrição do desvio"), responsible, { name: "dueAt", label: "Prazo", type: "datetime-local" }, { name: "classification", label: "Classificação", required: true, options: [{ value: "MINOR", label: "Menor" }, { value: "MAJOR", label: "Maior" }, { value: "CRITICAL", label: "Crítico" }] }]} />}</>}
    {resource === "action-plans" && <>{!["CONCLUIDO", "CANCELADO"].includes(status) && can("criar") && <CommandForm title="Adicionar ação 5W2H" endpoint={`${endpoint}/actions`} redirectResource="actions" fields={[textField("what", "O que será feito"), descriptionField("why", "Por quê"), textField("where", "Onde"), { name: "whenAt", label: "Quando", type: "datetime-local", required: true }, { ...responsible, name: "whoId", label: "Quem" }, descriptionField("how", "Como"), { ...numberField("howMuch", "Quanto custa"), min: 0 }]} />}{can("encerrar") && (related.actions ?? []).length > 0 && (related.actions ?? []).every(action => ["CONCLUIDO", "CANCELADO"].includes(str(action.status))) && <CommandForm title="Registrar verificação de eficácia" endpoint={`${endpoint}/effectiveness`} expectedVersion={version} fields={[{ name: "effective", label: "O plano foi eficaz?", required: true, options: [{ value: "true", label: "Sim, eficaz" }, { value: "false", label: "Não, exige nova ação" }] }, descriptionField("notes", "Justificativa da avaliação"), evidenceField]} transform={values => ({ ...values, effective: values.effective === "true" })} />}</>}
    {resource === "actions" && !["CONCLUIDO", "CANCELADO"].includes(status) && <>{can("editar") && <CommandForm title="Atualizar acompanhamento" endpoint={`${endpoint}/update`} expectedVersion={version} fields={[{ name: "status", label: "Situação", options: [{ value: "NAO_INICIADO", label: "Não iniciado" }, { value: "EM_ANDAMENTO", label: "Em andamento" }, { value: "BLOQUEADO", label: "Bloqueado" }], defaultValue: status }, { ...numberField("percentage", "Percentual concluído", false), min: 0, max: 99, defaultValue: str(row.percentage) }, descriptionField("blockedReason", "Motivo do bloqueio", false), descriptionField("comment", "Registro de acompanhamento", false)]} />}{can("encerrar") && <CommandForm title="Concluir ação" endpoint={`${endpoint}/complete`} expectedVersion={version} fields={[evidenceField]} />}</>}
    {resource === "meetings" && <>
      {!["COMPLETED", "CANCELLED"].includes(status) && (can("editar") || can("criar")) && <>{can("criar") && <CommandForm title="Adicionar item de pauta" endpoint={`${endpoint}/agenda`} fields={[{ ...numberField("position", "Ordem na pauta"), min: 1, max: 999, defaultValue: String((related.agenda ?? []).length + 1) }, textField("title", "Assunto"), descriptionField("description", "Contexto", false)]} />}{(choices.people ?? []).filter(person => can("criar") && (!(related.participants ?? []).some(participant => participant.user_id === person.id) || can("editar"))).map(person => <CommandForm key={person.id} title={`Registrar presença de ${person.name}`} endpoint={`${endpoint}/participants/${person.id}`} method="PUT" fields={[{ name: "attended", label: `Presença: ${person.name}`, required: true, options: [{ value: "true", label: "Presente" }, { value: "false", label: "Ausente" }], defaultValue: str((related.participants ?? []).find(participant => participant.user_id === person.id)?.attended) }]} transform={values => ({ attended: values.attended === "true" })} />)}{can("criar") && <CommandForm title="Criar encaminhamento" endpoint={`${endpoint}/referrals`} redirectResource="referrals" fields={[descriptionField("description", "Encaminhamento decidido"), responsible, { name: "agendaItemId", label: "Item da pauta", options: options(related.agenda) }, { name: "dueAt", label: "Prazo", type: "datetime-local", required: true }]} />}</>}
      {status === "SCHEDULED" && can("executar") && <CommandForm title="Iniciar reunião" endpoint={`${endpoint}/start`} expectedVersion={version} />}
      {["IN_PROGRESS", "MINUTES_PENDING"].includes(status) && can("encerrar") && <CommandForm title="Registrar ata e encerrar reunião" endpoint={`${endpoint}/complete`} expectedVersion={version} fields={[{ ...descriptionField("minutes", "Ata: discussões, decisões e encaminhamentos"), minLength: 10 }]} />}
    </>}
    {resource === "referrals" && !row.action_plan_id && ["OPEN", "IN_PROGRESS"].includes(status) && can("editar") && can("editar", "melhoria") && <CommandForm title="Converter encaminhamento em ação" endpoint={`${endpoint}/convert-to-action`} expectedVersion={version} redirectResource="action-plans" />}
    <RecordEvidence entityType={({ knowledge: "knowledge_items", "knowledge-versions": "knowledge_versions", "protocol-versions": "protocol_versions", "action-plans": "action_plans" } as Record<string, string>)[resource] ?? resource} entityId={row.id} organizationId={workspace.organizationId} unitId={row.unit_id ? str(row.unit_id) : null} attachments={files} canUpload={can("criar", "evidencias")} />
    {Object.entries(related).filter(([name]) => !["evidence", "attachments"].includes(name)).map(([name, rows]) => <section className="panel detail-section detail-relations" key={name}><h2>{({ "knowledge-versions": "Versões do conhecimento", "protocol-versions": "Versões do protocolo", forms: "Checklists", executions: "Execuções", formulas: "Fórmulas versionadas", targets: "Metas", measurements: "Medições", analyses: "Análises críticas", nonconformities: "Desvios", "action-plans": "Planos de ação", actions: "Ações", effectiveness: "Verificações de eficácia", agenda: "Pauta", participants: "Presenças", referrals: "Encaminhamentos", responses: "Respostas registradas", bindings: "Indicadores vinculados" } as Record<string, string>)[name] ?? name}</h2>{rows.length ? <ul>{rows.map(item => <li key={item.id}>{["knowledge-versions", "protocol-versions", "executions", "measurements", "nonconformities", "action-plans", "actions", "referrals"].includes(name) ? link(name, item.id, titleFor(item)) : name === "participants" ? <strong>{str(memberName(item.user_id))}</strong> : <strong>{name === "responses" ? str(item.field_key) : titleFor(item)}</strong>}<p>{[item.status && readable(item.status), item.value !== undefined && `Resultado: ${readable(item.value)}`, item.expression_ast && `Fórmula: ${readable(item.expression_ast)}`, item.target_value !== undefined && `Meta: ${readable(item.comparison)} ${readable(item.target_value)}`, item.analysis, item.decision, item.notes, item.description, item.attended !== undefined && `Presença: ${readable(item.attended)}`, item.schema && readable(item.schema)].filter(Boolean).join(" · ")}</p></li>)}</ul> : <p>Nenhum registro nesta etapa.</p>}</section>)}
  </div></DraftWorkspace.Provider>;
}
