import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { z } from "zod";
import { commandError } from "@/lib/server/command-response";
import { createSupabaseServerClient, isDemoMode, requireActor } from "@/lib/server/supabase";
const schema=z.object({email:z.email(),name:z.string().trim().min(2).max(160),organizationId:z.uuid(),unitId:z.uuid().nullable(),role:z.enum(["ADMIN_SISTEMA","GESTOR_ORGANIZACAO","GERENTE_UBS","RESPONSAVEL_DOMINIO","EXECUTOR","AUDITOR","LEITOR"]),domains:z.array(z.string().trim().min(1).max(80)).min(1).max(30),operations:z.array(z.enum(["visualizar","criar","editar","excluir_logicamente","aprovar","publicar","executar","encerrar","reabrir","exportar"])).min(1)});
export async function POST(request:Request){const actor=await requireActor();if(!actor)return NextResponse.json({error:"Não autenticado."},{status:401});const body=schema.safeParse(await request.json().catch(()=>null));if(!body.success)return NextResponse.json({error:"Convite inválido.",issues:body.error.issues},{status:422});if(isDemoMode())return NextResponse.json({id:crypto.randomUUID(),email:body.data.email,membershipId:crypto.randomUUID(),mode:"demo"},{status:201});
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!serviceKey)return NextResponse.json({error:"Serviço interno de convites não configurado."},{status:503});
 const caller=await createSupabaseServerClient();const{data:allowed}=await caller.from("memberships").select("id").eq("user_id",actor.id).eq("organization_id",body.data.organizationId).in("role",["ADMIN_SISTEMA","GESTOR_ORGANIZACAO","GERENTE_UBS"]).lte("starts_at",new Date().toISOString()).or(`ends_at.is.null,ends_at.gt.${new Date().toISOString()}`).limit(1);if(!allowed?.length)return NextResponse.json({error:"Sem permissão para convidar neste escopo."},{status:403});
 const admin=createClient(url,serviceKey,{auth:{autoRefreshToken:false,persistSession:false}});const redirectTo=`${process.env.NEXT_PUBLIC_APP_ORIGIN??new URL(request.url).origin}/login`;const{data:invitation,error:inviteError}=await admin.auth.admin.inviteUserByEmail(body.data.email,{redirectTo,data:{name:body.data.name}});if(inviteError||!invitation.user)return NextResponse.json({error:"Não foi possível enviar o convite."},{status:422});
 const{data:membershipId,error}=await caller.rpc("provision_invited_membership",{p_user_id:invitation.user.id,p_organization_id:body.data.organizationId,p_unit_id:body.data.unitId,p_role:body.data.role,p_domains:body.data.domains,p_operations:body.data.operations});return error?commandError(error):NextResponse.json({id:invitation.user.id,email:body.data.email,membershipId},{status:201});}
