import { beforeEach, describe, expect, it, vi } from 'vitest';
const mocks = vi.hoisted(() => ({ actor: vi.fn(), workspace: vi.fn(), rpc: vi.fn(), demo: vi.fn() }));
vi.mock('@/lib/server/supabase', () => ({ requireActor: mocks.actor, isDemoMode: mocks.demo, createSupabaseServerClient: async () => ({ rpc: mocks.rpc }) }));
vi.mock('@/lib/server/workspace', () => ({ loadWorkspaceContext: mocks.workspace }));
import { POST } from './route';
const organizationId = '00000000-0000-4000-8000-000000000010';
const unitId = '00000000-0000-4000-8000-000000000011';
const input = { organizationId, unitId, operationId: '00000000-0000-4000-8000-000000000099', entityId: '00000000-0000-4000-8000-000000000098', teamId: '00000000-0000-4000-8000-000000000101', expectedVersion: 0, occurredOn: '2026-09-09', procedureId: 'med-consulta', quantity: 3 };
const request = (body: unknown, origin = 'https://sgc.test') => new Request('https://sgc.test/api/v1/esf/production', { method: 'POST', headers: { origin, 'content-type': 'application/json' }, body: JSON.stringify(body) });
describe('ESF production API', () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.actor.mockResolvedValue({ id: 'actor' }); mocks.workspace.mockResolvedValue({ organizationId, unitId, enabledModules: ['formularios-esf'] }); mocks.demo.mockReturnValue(false); mocks.rpc.mockResolvedValue({ data: { id: input.entityId, version: 1 }, error: null }); });
  it('requires authentication', async () => { mocks.actor.mockResolvedValue(null); expect((await POST(request(input))).status).toBe(401); expect(mocks.rpc).not.toHaveBeenCalled(); });
  it('blocks cross-origin mutation', async () => { expect((await POST(request(input, 'https://other.test'))).status).toBe(403); expect(mocks.rpc).not.toHaveBeenCalled(); });
  it('blocks a different UBS', async () => { expect((await POST(request({ ...input, unitId: organizationId }))).status).toBe(403); expect(mocks.rpc).not.toHaveBeenCalled(); });
  it('blocks a different organization', async () => { expect((await POST(request({ ...input, organizationId: unitId }))).status).toBe(403); });
  it('rejects invalid quantities and unexpected nominal fields', async () => { expect((await POST(request({ ...input, quantity: 1.5 }))).status).toBe(422); expect((await POST(request({ ...input, name: 'Patient' }))).status).toBe(422); });
  it('uses the user-scoped transactional RPC and stable operation ID', async () => { expect((await POST(request(input))).status).toBe(200); expect(mocks.rpc).toHaveBeenCalledWith('save_esf_production', { p_operation_id: input.operationId, p_input: expect.objectContaining({ teamId: input.teamId, quantity: 3 }) }); });
  it('preserves PostgreSQL denials and version conflicts', async () => { mocks.rpc.mockResolvedValue({ error: { code: '42501' } }); expect((await POST(request(input))).status).toBe(403); mocks.rpc.mockResolvedValue({ error: { code: '40001' } }); expect((await POST(request(input))).status).toBe(409); });
  it('marks simulation explicitly and never invokes the database', async () => { mocks.demo.mockReturnValue(true); expect((await (await POST(request(input))).json()).mode).toBe('demo'); expect(mocks.rpc).not.toHaveBeenCalled(); });
});
