-- Complete governed lifecycles for knowledge and protocols.
create or replace function app.prevent_published_change() returns trigger language plpgsql set search_path=public,pg_temp as $$
declare old_data jsonb;new_data jsonb;obsolete_status text;
begin
  if old.status not in ('PUBLISHED','PUBLICADO') then return new;end if;
  if tg_op='DELETE' then raise exception 'Published versions are immutable' using errcode='55000';end if;
  obsolete_status:=case when old.status='PUBLICADO' then 'OBSOLETO' else 'OBSOLETE' end;
  old_data:=to_jsonb(old)-array['status','updated_at','updated_by'];new_data:=to_jsonb(new)-array['status','updated_at','updated_by'];
  if new.status<>obsolete_status or new_data<>old_data then raise exception 'Published versions are immutable; only controlled obsolescence is allowed' using errcode='55000';end if;return new;
end;$$;

create or replace function public.create_knowledge_version(p_item_id uuid,p_expected_version integer,p_operation_id uuid,p_content jsonb,p_references jsonb,p_valid_from date,p_valid_until date) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare item public.knowledge_items;prior jsonb;answer jsonb;version_id uuid;next_number integer;item_version integer;
begin
 select response into prior from public.idempotency_keys where operation_id=p_operation_id and user_id=auth.uid();if prior is not null then return prior||jsonb_build_object('duplicate',true);end if;select * into item from public.knowledge_items where id=p_item_id and deleted_at is null for update;if not found then raise exception 'Knowledge item not found' using errcode='P0002';end if;
 if not app.can_access(item.organization_id,item.unit_id,'conhecimento','editar') then raise exception 'Forbidden' using errcode='42501';end if;if item.version<>p_expected_version then raise exception 'Version conflict' using errcode='40001';end if;if jsonb_typeof(p_content)<>'object' or p_content='{}'::jsonb or jsonb_typeof(p_references)<>'array' or (p_valid_until is not null and p_valid_until<p_valid_from) then raise exception 'Invalid knowledge version' using errcode='22023';end if;
 select coalesce(max(version_number),0)+1 into next_number from public.knowledge_versions where knowledge_item_id=item.id;insert into public.knowledge_versions(organization_id,unit_id,knowledge_item_id,version_number,content,references_list,valid_from,valid_until,status,created_by) values(item.organization_id,item.unit_id,item.id,next_number,p_content,p_references,p_valid_from,p_valid_until,'DRAFT',auth.uid()) returning id into version_id;update public.knowledge_items set status='DRAFT',updated_by=auth.uid() where id=item.id returning version into item_version;
 answer:=jsonb_build_object('id',version_id,'knowledgeItemId',item.id,'versionNumber',next_number,'itemVersion',item_version,'status','DRAFT');insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response)values(p_operation_id,auth.uid(),item.organization_id,encode(digest(p_content::text,'sha256'),'hex'),answer);return answer;
end;$$;

create or replace function public.transition_knowledge_version(p_version_id uuid,p_expected_version_number integer,p_operation_id uuid,p_target_status text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.knowledge_versions;prior jsonb;answer jsonb;required_operation text;
begin
 select response into prior from public.idempotency_keys where operation_id=p_operation_id and user_id=auth.uid();if prior is not null then return prior||jsonb_build_object('duplicate',true);end if;select * into v from public.knowledge_versions where id=p_version_id for update;if not found then raise exception 'Knowledge version not found' using errcode='P0002';end if;if v.version_number<>p_expected_version_number then raise exception 'Version conflict' using errcode='40001';end if;
 required_operation:=case p_target_status when 'IN_REVIEW' then 'editar' when 'APPROVED' then 'aprovar' when 'PUBLISHED' then 'publicar' else null end;if required_operation is null or not app.can_access(v.organization_id,v.unit_id,'conhecimento',required_operation) then raise exception 'Forbidden or invalid transition' using errcode='42501';end if;
 if (p_target_status='IN_REVIEW' and v.status<>'DRAFT') or (p_target_status='APPROVED' and v.status<>'IN_REVIEW') or (p_target_status='PUBLISHED' and v.status<>'APPROVED') then raise exception 'Invalid knowledge transition' using errcode='22023';end if;
 if p_target_status='PUBLISHED' and (v.valid_from is null or jsonb_typeof(v.content)<>'object' or v.content='{}'::jsonb) then raise exception 'Required publication fields are missing' using errcode='22023';end if;
 if p_target_status='PUBLISHED' then update public.knowledge_versions set status='OBSOLETE' where knowledge_item_id=v.knowledge_item_id and status='PUBLISHED' and id<>v.id;end if;
 update public.knowledge_versions set status=p_target_status,approved_by=case when p_target_status='APPROVED' then auth.uid() else approved_by end,approved_at=case when p_target_status='APPROVED' then now() else approved_at end,published_at=case when p_target_status='PUBLISHED' then now() else published_at end where id=v.id;update public.knowledge_items set status=p_target_status,updated_by=auth.uid() where id=v.knowledge_item_id;
 answer:=jsonb_build_object('id',v.id,'status',p_target_status,'version',v.version_number);insert into public.domain_events(organization_id,unit_id,event_type,aggregate_type,aggregate_id,aggregate_version,actor_id,payload)values(v.organization_id,v.unit_id,case p_target_status when 'PUBLISHED' then 'KnowledgePublished' else 'KnowledgeStatusChanged' end,'conhecimento',v.knowledge_item_id,v.version_number,auth.uid(),answer);insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response)values(p_operation_id,auth.uid(),v.organization_id,encode(digest(answer::text,'sha256'),'hex'),answer);return answer;
end;$$;

create or replace function public.create_protocol_version(p_protocol_id uuid,p_expected_version integer,p_operation_id uuid,p_content jsonb,p_valid_from date,p_valid_until date) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare protocol public.protocols;prior jsonb;answer jsonb;version_id uuid;next_number integer;protocol_version integer;
begin
 select response into prior from public.idempotency_keys where operation_id=p_operation_id and user_id=auth.uid();if prior is not null then return prior||jsonb_build_object('duplicate',true);end if;select * into protocol from public.protocols where id=p_protocol_id and deleted_at is null for update;if not found then raise exception 'Protocol not found' using errcode='P0002';end if;if not app.can_access(protocol.organization_id,protocol.unit_id,'protocolos','editar') then raise exception 'Forbidden' using errcode='42501';end if;if protocol.version<>p_expected_version then raise exception 'Version conflict' using errcode='40001';end if;if jsonb_typeof(p_content)<>'object' or p_content='{}'::jsonb or (p_valid_until is not null and p_valid_until<p_valid_from) then raise exception 'Invalid protocol version' using errcode='22023';end if;
 select coalesce(max(version_number),0)+1 into next_number from public.protocol_versions where protocol_id=protocol.id;insert into public.protocol_versions(organization_id,unit_id,protocol_id,version_number,content,valid_from,valid_until,status,created_by)values(protocol.organization_id,protocol.unit_id,protocol.id,next_number,p_content,p_valid_from,p_valid_until,'RASCUNHO',auth.uid())returning id into version_id;update public.protocols set status='RASCUNHO',updated_by=auth.uid() where id=protocol.id returning version into protocol_version;answer:=jsonb_build_object('id',version_id,'protocolId',protocol.id,'versionNumber',next_number,'protocolVersion',protocol_version,'status','RASCUNHO');insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response)values(p_operation_id,auth.uid(),protocol.organization_id,encode(digest(p_content::text,'sha256'),'hex'),answer);return answer;
end;$$;

create or replace function public.submit_protocol_review(p_version_id uuid,p_expected_version_number integer,p_operation_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.protocol_versions;prior jsonb;answer jsonb;
begin select response into prior from public.idempotency_keys where operation_id=p_operation_id and user_id=auth.uid();if prior is not null then return prior||jsonb_build_object('duplicate',true);end if;select * into v from public.protocol_versions where id=p_version_id for update;if not found then raise exception 'Protocol version not found' using errcode='P0002';end if;if not app.can_access(v.organization_id,v.unit_id,'protocolos','editar') then raise exception 'Forbidden' using errcode='42501';end if;if v.version_number<>p_expected_version_number then raise exception 'Version conflict' using errcode='40001';end if;if v.status<>'RASCUNHO' or jsonb_typeof(v.content)<>'object' or v.content='{}'::jsonb then raise exception 'Invalid protocol review submission' using errcode='22023';end if;update public.protocol_versions set status='EM_REVISAO' where id=v.id;update public.protocols set status='EM_REVISAO',updated_by=auth.uid() where id=v.protocol_id;answer:=jsonb_build_object('id',v.id,'status','EM_REVISAO','version',v.version_number);insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response)values(p_operation_id,auth.uid(),v.organization_id,encode(digest(answer::text,'sha256'),'hex'),answer);return answer;end;$$;

create or replace function public.start_protocol_execution(p_execution_id uuid,p_protocol_version_id uuid,p_unit_id uuid,p_operation_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v public.protocol_versions;prior jsonb;answer jsonb;execution_version integer;
begin select response into prior from public.idempotency_keys where operation_id=p_operation_id and user_id=auth.uid();if prior is not null then return prior||jsonb_build_object('duplicate',true);end if;select * into v from public.protocol_versions where id=p_protocol_version_id;if not found then raise exception 'Protocol version not found' using errcode='P0002';end if;if v.status<>'PUBLICADO' or (v.valid_from is not null and v.valid_from>current_date) or (v.valid_until is not null and v.valid_until<current_date) then raise exception 'Protocol version is not currently published' using errcode='22023';end if;if not app.can_access(v.organization_id,p_unit_id,'protocolos','executar') then raise exception 'Forbidden' using errcode='42501';end if;if v.unit_id is not null and v.unit_id<>p_unit_id then raise exception 'Protocol is not applicable to this unit' using errcode='42501';end if;
 insert into public.executions(id,organization_id,unit_id,protocol_version_id,executor_id,status,started_at,created_by,updated_by)values(p_execution_id,v.organization_id,p_unit_id,v.id,auth.uid(),'IN_PROGRESS',now(),auth.uid(),auth.uid())returning version into execution_version;answer:=jsonb_build_object('id',p_execution_id,'protocolVersionId',v.id,'status','IN_PROGRESS','version',execution_version,'startedAt',now());insert into public.domain_events(organization_id,unit_id,event_type,aggregate_type,aggregate_id,aggregate_version,actor_id,payload)values(v.organization_id,p_unit_id,'ProtocolExecutionStarted','protocolos',p_execution_id,execution_version,auth.uid(),jsonb_build_object('protocolVersionId',v.id));insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response)values(p_operation_id,auth.uid(),v.organization_id,encode(digest(answer::text,'sha256'),'hex'),answer);return answer;end;$$;

revoke all on function public.create_knowledge_version(uuid,integer,uuid,jsonb,jsonb,date,date) from public,anon;grant execute on function public.create_knowledge_version(uuid,integer,uuid,jsonb,jsonb,date,date) to authenticated;
revoke all on function public.transition_knowledge_version(uuid,integer,uuid,text) from public,anon;grant execute on function public.transition_knowledge_version(uuid,integer,uuid,text) to authenticated;
revoke all on function public.create_protocol_version(uuid,integer,uuid,jsonb,date,date) from public,anon;grant execute on function public.create_protocol_version(uuid,integer,uuid,jsonb,date,date) to authenticated;
revoke all on function public.submit_protocol_review(uuid,integer,uuid) from public,anon;grant execute on function public.submit_protocol_review(uuid,integer,uuid) to authenticated;
revoke all on function public.start_protocol_execution(uuid,uuid,uuid,uuid) from public,anon;grant execute on function public.start_protocol_execution(uuid,uuid,uuid,uuid) to authenticated;
