-- Private evidence lifecycle with verified finalization and audited access.
create table public.attachment_access_log(id bigint generated always as identity primary key,organization_id uuid not null references public.organizations(id),unit_id uuid,attachment_id uuid not null references public.attachments(id),actor_id uuid not null references auth.users(id),device_id uuid,purpose text not null,accessed_at timestamptz not null default now(),foreign key(organization_id,unit_id) references public.units(organization_id,id));
alter table public.attachment_access_log enable row level security;create policy attachment_access_log_select on public.attachment_access_log for select to authenticated using(app.can_access(organization_id,unit_id,'auditoria','visualizar'));grant select on public.attachment_access_log to authenticated;create trigger attachment_access_log_append_only before update or delete on public.attachment_access_log for each row execute function app.reject_audit_mutation();

create or replace function public.reserve_attachment(p_attachment_id uuid,p_organization_id uuid,p_unit_id uuid,p_object_path text,p_file_name text,p_content_type text,p_byte_size bigint,p_sha256 text,p_classification text,p_entity_type text,p_entity_id uuid,p_evidence_kind text) returns jsonb language plpgsql security invoker set search_path=public,pg_temp as $$
begin if not app.can_access(p_organization_id,p_unit_id,'evidencias','criar') then raise exception 'Forbidden' using errcode='42501';end if;insert into public.attachments(id,organization_id,unit_id,bucket,object_path,file_name,content_type,byte_size,sha256,classification,status,created_by,updated_by)values(p_attachment_id,p_organization_id,p_unit_id,'evidence',p_object_path,p_file_name,p_content_type,p_byte_size,lower(p_sha256),p_classification,'PENDING',auth.uid(),auth.uid());insert into public.evidence_links(organization_id,unit_id,attachment_id,entity_type,entity_id,evidence_kind,created_by)values(p_organization_id,p_unit_id,p_attachment_id,p_entity_type,p_entity_id,p_evidence_kind,auth.uid());return jsonb_build_object('id',p_attachment_id,'status','PENDING','version',1);end;$$;

create or replace function public.finalize_attachment(p_attachment_id uuid,p_expected_version integer,p_observed_size bigint,p_observed_sha256 text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare attachment public.attachments;next_version integer;
begin select * into attachment from public.attachments where id=p_attachment_id for update;if not found then raise exception 'Attachment not found' using errcode='P0002';end if;if not app.can_access(attachment.organization_id,attachment.unit_id,'evidencias','criar') then raise exception 'Forbidden' using errcode='42501';end if;if attachment.created_by<>auth.uid() or attachment.version<>p_expected_version or attachment.status<>'PENDING' then raise exception 'Attachment cannot be finalized' using errcode='40001';end if;if attachment.byte_size<>p_observed_size or lower(attachment.sha256)<>lower(p_observed_sha256) then update public.attachments set status='QUARANTINED',updated_by=auth.uid() where id=attachment.id;raise exception 'Attachment integrity mismatch' using errcode='22000';end if;update public.attachments set status='AVAILABLE',updated_by=auth.uid() where id=attachment.id returning version into next_version;insert into public.domain_events(organization_id,unit_id,event_type,aggregate_type,aggregate_id,aggregate_version,actor_id,payload)values(attachment.organization_id,attachment.unit_id,'EvidenceAttached','evidencias',attachment.id,next_version,auth.uid(),jsonb_build_object('classification',attachment.classification,'byteSize',attachment.byte_size));return jsonb_build_object('id',attachment.id,'status','AVAILABLE','version',next_version);end;$$;
create or replace function public.record_attachment_access(p_attachment_id uuid,p_device_id uuid,p_purpose text) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare attachment public.attachments;begin select * into attachment from public.attachments where id=p_attachment_id and status='AVAILABLE' and deleted_at is null;if not found then raise exception 'Attachment not found' using errcode='P0002';end if;if not app.can_access(attachment.organization_id,attachment.unit_id,'evidencias','visualizar') or length(trim(coalesce(p_purpose,'')))<3 then raise exception 'Forbidden' using errcode='42501';end if;insert into public.attachment_access_log(organization_id,unit_id,attachment_id,actor_id,device_id,purpose)values(attachment.organization_id,attachment.unit_id,attachment.id,auth.uid(),p_device_id,p_purpose);end;$$;
revoke all on function public.reserve_attachment(uuid,uuid,uuid,text,text,text,bigint,text,text,text,uuid,text) from public,anon;grant execute on function public.reserve_attachment(uuid,uuid,uuid,text,text,text,bigint,text,text,text,uuid,text) to authenticated;revoke all on function public.finalize_attachment(uuid,integer,bigint,text) from public,anon;grant execute on function public.finalize_attachment(uuid,integer,bigint,text) to authenticated;revoke all on function public.record_attachment_access(uuid,uuid,text) from public,anon;grant execute on function public.record_attachment_access(uuid,uuid,text) to authenticated;
