-- Never trust tenant or domain identifiers supplied by an offline client.
create or replace function public.apply_sync_batch(p_batch jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare op jsonb;prior jsonb;action_row public.actions;execution_row public.executions;result jsonb:='[]'::jsonb;op_response jsonb;next_version integer;claimed_org uuid;claimed_unit uuid;v_operation_id uuid;v_device_id uuid;v_entity_id uuid;
begin
  if jsonb_typeof(p_batch->'operations')<>'array' or jsonb_array_length(p_batch->'operations') not between 1 and 100 then raise exception 'Invalid sync batch' using errcode='22023';end if;
  for op in select value from jsonb_array_elements(p_batch->'operations') loop
    v_operation_id:=(op->>'operationId')::uuid;v_device_id:=(op->>'deviceId')::uuid;v_entity_id:=(op->>'entityId')::uuid;claimed_org:=(op->>'organizationId')::uuid;claimed_unit:=nullif(op->>'unitId','')::uuid;
    select k.response into prior from public.idempotency_keys k where k.operation_id=v_operation_id and k.user_id=auth.uid();if prior is not null then result:=result||jsonb_build_array(prior||jsonb_build_object('status','duplicate'));continue;end if;
    if not exists(select 1 from public.devices d where d.id=v_device_id and d.user_id=auth.uid() and d.organization_id=claimed_org and d.revoked_at is null and d.last_verified_at>now()-interval '72 hours') then op_response:=jsonb_build_object('operationId',v_operation_id,'status','rejected','reason','device_invalid_or_expired');
    elsif op->>'command'='ACTION_UPDATE_PROGRESS' then
      select * into action_row from public.actions where id=v_entity_id and organization_id=claimed_org and unit_id is not distinct from claimed_unit and deleted_at is null for update;
      if not found or not app.can_access(action_row.organization_id,action_row.unit_id,'melhoria','editar') then op_response:=jsonb_build_object('operationId',v_operation_id,'status','rejected','reason','entity_scope_forbidden');
      elsif action_row.version<>(op->>'expectedVersion')::integer then insert into public.sync_conflicts(organization_id,unit_id,entity_type,entity_id,operation_id,expected_version,server_version,client_payload,server_payload) values(action_row.organization_id,action_row.unit_id,'melhoria',action_row.id,v_operation_id,(op->>'expectedVersion')::integer,action_row.version,op->'payload',to_jsonb(action_row));op_response:=jsonb_build_object('operationId',v_operation_id,'status','conflict','serverVersion',action_row.version);
      elsif coalesce((op->'payload'->>'percentage')::integer,-1) not between 0 and 100 or coalesce(op->'payload'->>'status','NAO_INICIADO') not in ('NAO_INICIADO','EM_ANDAMENTO','BLOQUEADO') then op_response:=jsonb_build_object('operationId',v_operation_id,'status','rejected','reason','invalid_payload');
      else update public.actions set percentage=(op->'payload'->>'percentage')::integer,status=coalesce(op->'payload'->>'status',status),blocked_reason=case when op->'payload'->>'status'='BLOQUEADO' then nullif(op->'payload'->>'blockedReason','') else null end,updated_by=auth.uid() where id=action_row.id returning version into next_version;op_response:=jsonb_build_object('operationId',v_operation_id,'status','accepted','serverVersion',next_version);end if;
    elsif op->>'command'='EXECUTION_SAVE_DRAFT' then
      select * into execution_row from public.executions where id=v_entity_id and organization_id=claimed_org and unit_id is not distinct from claimed_unit and deleted_at is null for update;
      if not found or not app.can_access(execution_row.organization_id,execution_row.unit_id,'protocolos','executar') then op_response:=jsonb_build_object('operationId',v_operation_id,'status','rejected','reason','entity_scope_forbidden');
      elsif execution_row.version<>(op->>'expectedVersion')::integer then insert into public.sync_conflicts(organization_id,unit_id,entity_type,entity_id,operation_id,expected_version,server_version,client_payload,server_payload) values(execution_row.organization_id,execution_row.unit_id,'protocolos',execution_row.id,v_operation_id,(op->>'expectedVersion')::integer,execution_row.version,op->'payload',to_jsonb(execution_row));op_response:=jsonb_build_object('operationId',v_operation_id,'status','conflict','serverVersion',execution_row.version);
      elsif jsonb_typeof(op->'payload'->'result') is distinct from 'object' then op_response:=jsonb_build_object('operationId',v_operation_id,'status','rejected','reason','invalid_payload');
      else update public.executions set result=op->'payload'->'result',notes=left(coalesce(op->'payload'->>'notes',''),10000),status='PENDING_SYNC',updated_by=auth.uid() where id=execution_row.id returning version into next_version;op_response:=jsonb_build_object('operationId',v_operation_id,'status','accepted','serverVersion',next_version);end if;
    else op_response:=jsonb_build_object('operationId',v_operation_id,'status','rejected','reason','unsupported_command');end if;
    insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response) values(v_operation_id,auth.uid(),claimed_org,encode(digest(op::text,'sha256'),'hex'),op_response);result:=result||jsonb_build_array(op_response);
  end loop;return jsonb_build_object('cursor',now(),'results',result);
end;$$;
revoke all on function public.apply_sync_batch(jsonb) from public,anon;grant execute on function public.apply_sync_batch(jsonb) to authenticated;
