-- Critical analysis, governed action updates and internal pending inbox.
alter table public.critical_analyses add column action_plan_id uuid references public.action_plans(id),add column version integer not null default 1,add column updated_at timestamptz not null default now(),add column updated_by uuid references auth.users(id),add constraint critical_analyses_measurement_unique unique(measurement_id);
create trigger critical_analyses_touch before update on public.critical_analyses for each row execute function app.touch_version();create trigger critical_analyses_audit after insert or update or delete on public.critical_analyses for each row execute function app.audit_change('');drop trigger if exists critical_analyses_outbox on public.critical_analyses;create trigger critical_analyses_outbox after insert or update or delete on public.critical_analyses for each row execute function app.emit_domain_change('indicadores');

create table public.action_comments(id uuid primary key default gen_random_uuid(),organization_id uuid not null,unit_id uuid not null,action_id uuid not null references public.actions(id),comment text not null,created_at timestamptz not null default now(),created_by uuid not null references auth.users(id),foreign key(organization_id,unit_id) references public.units(organization_id,id));
alter table public.action_comments enable row level security;create policy action_comments_select on public.action_comments for select to authenticated using(app.can_access(organization_id,unit_id,'melhoria','visualizar'));create policy action_comments_insert on public.action_comments for insert to authenticated with check(created_by=auth.uid() and app.can_access(organization_id,unit_id,'melhoria','editar'));grant select,insert on public.action_comments to authenticated;create trigger action_comments_scope before insert or update of organization_id,unit_id,action_id on public.action_comments for each row execute function app.assert_reference_scope('actions','action_id');create trigger action_comments_audit after insert or delete on public.action_comments for each row execute function app.audit_change('');create trigger action_comments_outbox after insert or delete on public.action_comments for each row execute function app.emit_domain_change('melhoria');

create or replace function public.record_critical_analysis(p_measurement_id uuid,p_expected_version integer,p_operation_id uuid,p_analysis text,p_cause text,p_decision text,p_action_plan_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare measurement public.measurements;plan public.action_plans;prior jsonb;answer jsonb;analysis_id uuid;
begin select response into prior from public.idempotency_keys where operation_id=p_operation_id and user_id=auth.uid();if prior is not null then return prior||jsonb_build_object('duplicate',true);end if;select * into measurement from public.measurements where id=p_measurement_id for update;if not found then raise exception 'Measurement not found' using errcode='P0002';end if;if not app.can_access(measurement.organization_id,measurement.unit_id,'indicadores','editar') then raise exception 'Forbidden' using errcode='42501';end if;if measurement.version<>p_expected_version then raise exception 'Version conflict' using errcode='40001';end if;if length(trim(coalesce(p_analysis,'')))<3 or length(trim(coalesce(p_decision,'')))<3 then raise exception 'Analysis and decision are required' using errcode='22023';end if;if p_action_plan_id is not null then select * into plan from public.action_plans where id=p_action_plan_id;if not found or plan.organization_id<>measurement.organization_id or plan.unit_id<>measurement.unit_id then raise exception 'Action plan scope mismatch' using errcode='23514';end if;end if;insert into public.critical_analyses(organization_id,unit_id,measurement_id,analysis,cause,decision,action_plan_id,created_by,updated_by)values(measurement.organization_id,measurement.unit_id,measurement.id,p_analysis,p_cause,p_decision,p_action_plan_id,auth.uid(),auth.uid())on conflict(measurement_id) do update set analysis=excluded.analysis,cause=excluded.cause,decision=excluded.decision,action_plan_id=excluded.action_plan_id,updated_by=auth.uid() returning id into analysis_id;answer:=jsonb_build_object('id',analysis_id,'measurementId',measurement.id,'actionPlanId',p_action_plan_id);insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response)values(p_operation_id,auth.uid(),measurement.organization_id,encode(digest(answer::text,'sha256'),'hex'),answer);return answer;end;$$;

create or replace function public.update_action(p_action_id uuid,p_expected_version integer,p_operation_id uuid,p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare action public.actions;prior jsonb;answer jsonb;next_version integer;new_status text;new_percentage integer;new_due timestamptz;new_responsible uuid;justification text;
begin select response into prior from public.idempotency_keys where operation_id=p_operation_id and user_id=auth.uid();if prior is not null then return prior||jsonb_build_object('duplicate',true);end if;select * into action from public.actions where id=p_action_id and deleted_at is null for update;if not found then raise exception 'Action not found' using errcode='P0002';end if;if not app.can_access(action.organization_id,action.unit_id,'melhoria','editar') then raise exception 'Forbidden' using errcode='42501';end if;if action.version<>p_expected_version then raise exception 'Version conflict' using errcode='40001';end if;if action.status in ('CONCLUIDO','CANCELADO') then raise exception 'Closed action cannot be edited' using errcode='22023';end if;
 new_status:=coalesce(p_payload->>'status',action.status);new_percentage:=coalesce((p_payload->>'percentage')::integer,action.percentage);new_due:=case when p_payload?'dueAt' then nullif(p_payload->>'dueAt','')::timestamptz else action.when_at end;new_responsible:=case when p_payload?'responsibleId' then nullif(p_payload->>'responsibleId','')::uuid else action.who_id end;justification:=nullif(trim(p_payload->>'justification'),'');
 if new_status not in ('NAO_INICIADO','EM_ANDAMENTO','BLOQUEADO') or new_percentage not between 0 and 99 then raise exception 'Invalid action state or progress' using errcode='22023';end if;if new_status='BLOQUEADO' and length(trim(coalesce(p_payload->>'blockedReason','')))<3 then raise exception 'Blocked reason is required' using errcode='22023';end if;if new_due is distinct from action.when_at and length(coalesce(justification,''))<3 then raise exception 'Due date change requires justification' using errcode='22023';end if;if new_responsible is distinct from action.who_id and length(coalesce(justification,''))<3 then raise exception 'Responsible change requires justification' using errcode='22023';end if;
 update public.actions set status=new_status,percentage=new_percentage,when_at=new_due,who_id=new_responsible,blocked_reason=case when new_status='BLOQUEADO' then p_payload->>'blockedReason' else null end,updated_by=auth.uid() where id=action.id returning version into next_version;if length(trim(coalesce(p_payload->>'comment','')))>=1 then insert into public.action_comments(organization_id,unit_id,action_id,comment,created_by)values(action.organization_id,action.unit_id,action.id,p_payload->>'comment',auth.uid());end if;if justification is not null then insert into public.action_comments(organization_id,unit_id,action_id,comment,created_by)values(action.organization_id,action.unit_id,action.id,'Justificativa de alteração: '||justification,auth.uid());end if;answer:=jsonb_build_object('id',action.id,'status',new_status,'percentage',new_percentage,'dueAt',new_due,'responsibleId',new_responsible,'version',next_version);insert into public.idempotency_keys(operation_id,user_id,organization_id,request_hash,response)values(p_operation_id,auth.uid(),action.organization_id,encode(digest(p_payload::text,'sha256'),'hex'),answer);return answer;end;$$;

create or replace function public.mark_notification_read(p_notification_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare notification public.notifications;begin select * into notification from public.notifications where id=p_notification_id for update;if not found then raise exception 'Notification not found' using errcode='P0002';end if;if notification.user_id<>auth.uid() and not app.can_access(notification.organization_id,notification.unit_id,'notificacoes','editar') then raise exception 'Forbidden' using errcode='42501';end if;update public.notifications set read_at=coalesce(read_at,now()) where id=notification.id;return jsonb_build_object('id',notification.id,'readAt',coalesce(notification.read_at,now()),'resolved',notification.resolved_at is not null,'severity',notification.severity);end;$$;

revoke all on function public.record_critical_analysis(uuid,integer,uuid,text,text,text,uuid) from public,anon;grant execute on function public.record_critical_analysis(uuid,integer,uuid,text,text,text,uuid) to authenticated;revoke all on function public.update_action(uuid,integer,uuid,jsonb) from public,anon;grant execute on function public.update_action(uuid,integer,uuid,jsonb) to authenticated;revoke all on function public.mark_notification_read(uuid) from public,anon;grant execute on function public.mark_notification_read(uuid) to authenticated;
